version: '3.9'
services:
  satisfactory-server:
    image: 'satisfactory-arm64'
    container_name: 'satisfactory-server'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
      - '8888:8888/tcp'
    restart: 'unless-stopped'
    environment:
      - EXTRA_PARAMS=-log -unattended -ini:Engine:[HTTPServer.Listeners]:DefaultBindAddress=any
    volumes:
      - './satisfactory:/satisfactory'
      - './config:/home/steam/.config/Epic'
